### ISSUE TITLE
Use current base library from Uber iOSSnapshotTestCase instead of the FB which is not mainteined anymore?

### ISSUE THREAD

**Issue by f-gonzalez** [AndriiDoroshko/SnappyShrimp#4]
Uber took the original FB Snapshot code and its maintining it, renamed to iOSSnapshotTestCase:
https://github.com/uber/ios-snapshot-test-case/

Also, it would be great to be able to install SnappyShrimp using cocoapods!

**Comment by balavor** [comment]
@f-gonzalez Thanks for your feedback. We know that uber maintains that framework, but it didn't bring anything new to it yet. Also we are planning to add some improvements to make it work better.

**Comment by f-gonzalez** [comment]
ok great! thanks @RomanTysiachnik

**Comment by balavor** [comment]
@f-gonzalez hi. I'm still not sure if we're going to add Cocoapods in the nearest time. So if you will have some free time, feel free to contribute ;)
